"""Read a score back into MSN, so the composer can see what is on the page.

This is how Motif reads a musician's own music: MuseScore hands over
MusicXML, the reader turns it into Motif's score model, and this writes it
in the same notation the composer itself composes in — every note, voice,
tie, slur, dynamic and pedal mark — in concert pitch. A continuation or a
revision then starts from the music as it really is, not from a summary.
"""
from __future__ import annotations

import re
from fractions import Fraction

from ..score import DIVISIONS, Direction, Note, Part, Score
from ..theory.pitch import Interval, Key, Pitch
from .instruments import Instrument, PartSpec, by_program, instrument
from .msn import (DURATION_LETTERS, MARK_NAMES, RESERVED_IDS, Event, Marking,
                  MsnMeasure, MsnPiece, VoiceLine, bar_length, render)

_TYPE_QUARTERS = {"breve": Fraction(8), "whole": Fraction(4), "half": Fraction(2),
                  "quarter": Fraction(1), "eighth": Fraction(1, 2), "16th": Fraction(1, 4),
                  "32nd": Fraction(1, 8), "64th": Fraction(1, 16)}


def score_to_msn(score: Score) -> str:
    return render(from_score(score))


def from_score(score: Score) -> MsnPiece:
    piece = MsnPiece(title=score.title or "Untitled", subtitle=score.subtitle or "",
                     composer=score.composer if score.composer not in (
                         "Unknown", "Generated by Motif.ai") else "",
                     time=tuple(score.time))
    specs = _part_specs(score)
    piece.parts = specs
    if not score.parts:
        return piece
    first = score.parts[0]
    concert_key = _concert_key(first, first.measures[0].key if first.measures and
                               first.measures[0].key else score.key)
    piece.key = concert_key

    visible = sorted([t for t in score.tempos if t.visible], key=lambda t: (t.measure, t.offset))
    head_tempo = next((t for t in visible if t.measure == 1 or t.measure == 0), None)
    if head_tempo is not None:
        piece.tempo = head_tempo.bpm
        piece.tempo_text = head_tempo.text
    else:
        piece.tempo = score.tempo

    count = max(len(p.measures) for p in score.parts)
    time = tuple(score.time)
    first_len = _written_length(first.measures[0]) if first.measures else 0
    pickup = bool(first.measures) and (
        first.measures[0].implicit or (0 < first_len < _ticks(bar_length(time))))
    base_number = 0 if pickup else 1
    prev_key = concert_key

    voice_maps = [_voice_map(p) for p in score.parts]
    for i in range(count):
        number = base_number + i
        ref = first.measures[i] if i < len(first.measures) else None
        mm = MsnMeasure(number=number)
        if ref is not None:
            if ref.time and i > 0:
                mm.time = tuple(ref.time)
                time = mm.time
            if ref.key is not None and i > 0:
                k = _concert_key(first, ref.key)
                if str(k) != str(prev_key):
                    mm.key = k
                    prev_key = k
            _bar_attrs(mm, ref, i == count - 1)
        for t in visible:
            if t is head_tempo or t.measure != (ref.number if ref is not None else i + 1):
                continue
            if t.offset == 0:
                mm.tempo, mm.tempo_text = t.bpm, t.text
        for pi, (part, spec) in enumerate(zip(score.parts, specs)):
            if i >= len(part.measures):
                continue
            m = part.measures[i]
            if m.clefs and i > 0:
                for staff, clef in m.clefs.items():
                    mm.clefs[(spec.id, staff)] = clef
            _measure_voices(mm, part, spec, m, voice_maps[pi], time)
            if pi == 0:
                for d in m.directions:
                    if d.kind == "rehearsal" and not mm.mark:
                        mm.mark = d.value
        piece.measures.append(mm)
    return piece


# ---------------------------------------------------------------------------
def _part_specs(score: Score) -> list[PartSpec]:
    specs: list[PartSpec] = []
    used: set[str] = set()
    for part in score.parts:
        inst = (instrument(part.extra.get("instrument")) if part.extra.get("instrument")
                else None) or instrument(part.name) or by_program(part.midi_program, part.staves)
        if inst is None or inst.staves != max(1, part.staves):
            inst = _custom_instrument(part, inst)
        pid = part.extra.get("msn_id") or _short_id(part, inst)
        base, n = pid, 2
        while (pid in used or pid.upper() in RESERVED_IDS or re.match(r"^[mM]\d+$", pid)
               or re.match(r"^(RH|LH|PED|UP|LOW)\d*$", pid, re.I)):
            pid = f"{base}{n}"
            n += 1
        used.add(pid)
        name = part.name if part.name and part.name != inst.name else ""
        specs.append(PartSpec(pid, inst, name))
    return specs


def _custom_instrument(part: Part, near: Instrument | None) -> Instrument:
    lo, hi = 127, 0
    for m in part.measures:
        for notes in m.voices.values():
            for n in notes:
                for p in n.pitches:
                    lo, hi = min(lo, p.midi), max(hi, p.midi)
    if lo > hi:
        lo, hi = (21, 108) if part.staves > 1 else (48, 84)
    clefs = tuple(part.clefs.get(i + 1, "G" if i == 0 else "F")
                  for i in range(max(1, part.staves)))
    key = re.sub(r"[^a-z0-9]+", "_", (part.name or "part").lower()).strip("_") or "part"
    return Instrument(key, part.name or "Part", part.abbreviation or part.name[:4],
                      part.midi_program, max(0, lo - 2), min(127, hi + 2), clefs,
                      near.family if near else "other",
                      near.sound if near else "keyboard.piano",
                      keyboard=part.staves > 1)


def _short_id(part: Part, inst: Instrument) -> str:
    raw = re.sub(r"[^A-Za-z0-9]", "", inst.abbreviation or inst.key)[:4] or "P"
    if not raw[0].isalpha():
        raw = "P" + raw
    return raw[0].upper() + raw[1:]


def _concert_key(part: Part, key: Key) -> Key:
    if not part.transpose:
        return key
    diatonic, chromatic, octave = part.transpose
    tonic = Pitch.parse(key.tonic + "4").transpose_by(Interval(diatonic, chromatic))
    from .to_score import _sane_key
    return _sane_key(tonic.name, key.mode)


def _to_concert(part: Part, p: Pitch) -> Pitch:
    if not part.transpose:
        return p
    diatonic, chromatic, octave = part.transpose
    c = p.transpose_by(Interval(diatonic + 7 * octave, chromatic + 12 * octave))
    return c


def _bar_attrs(mm: MsnMeasure, m, last: bool) -> None:
    if m.barline in ("light-light",):
        mm.barline = "double"
    elif m.barline in ("light-heavy",) and not last:
        mm.barline = "final"
    elif m.barline == "dashed":
        mm.barline = "dashed"
    if m.repeat_start and m.repeat_end:
        mm.repeat = "both"
    elif m.repeat_start:
        mm.repeat = "start"
    elif m.repeat_end:
        mm.repeat = "end"
    if m.ending:
        mm.ending = m.ending


def _voice_map(part: Part) -> dict[int, tuple[int, int]]:
    """MusicXML voice number -> (staff, voice 1..4), consistent through the part."""
    per_staff: dict[int, set[int]] = {}
    for m in part.measures:
        for v, notes in m.voices.items():
            real = [n for n in notes if not n.grace]
            if not real:
                continue
            staff = max(1, min(max(1, part.staves), real[0].staff))
            per_staff.setdefault(staff, set()).add(v)
    out: dict[int, tuple[int, int]] = {}
    for staff, voices in per_staff.items():
        for i, v in enumerate(sorted(voices)):
            out[v] = (staff, min(4, i + 1))
    return out


def _ticks(q: Fraction) -> int:
    return int(round(q * DIVISIONS))


def _written_length(m) -> int:
    return max((sum(n.duration for n in notes if not n.grace)
                for notes in m.voices.values()), default=0)


def _measure_voices(mm: MsnMeasure, part: Part, spec: PartSpec, m, vmap, time) -> None:
    lines: dict[tuple[int, int], VoiceLine] = {}
    for v, notes in sorted(m.voices.items()):
        real = [n for n in notes if not n.grace]
        if not real and not notes:
            continue
        staff, voice = vmap.get(v, (max(1, notes[0].staff), 1))
        key = (staff, voice)
        if key in lines:
            continue                           # two source voices mapped together: keep the first
        vl = VoiceLine(label="", part=spec.id, staff=staff, voice=voice)
        vl.items = _events(part, notes, time, bar_len=_ticks(bar_length(time)),
                           first_voice=(voice == 1))
        lines[key] = vl
    # Every staff needs its first voice, even if the source left it empty.
    for staff in range(1, spec.staves + 1):
        if (staff, 1) not in lines:
            vl = VoiceLine(label="", part=spec.id, staff=staff, voice=1)
            vl.items = [Event(kind="bar_rest")]
            lines[(staff, 1)] = vl
    _place_directions(lines, spec, m)
    for (staff, voice), vl in sorted(lines.items()):
        pos = Fraction(0)
        for it in vl.items:
            if isinstance(it, Event):
                it.offset = pos
                if it.kind != "bar_rest":
                    pos += it.duration
        mm.voices.append(vl)


def _events(part: Part, notes: list[Note], time, bar_len: int, first_voice: bool) -> list:
    out: list = []
    graces: list[Event] = []
    grace_slash = False
    real = [n for n in notes if not n.grace]
    if (len(real) == 1 and real[0].is_rest and
            (real[0].measure_rest or real[0].duration >= bar_len) and first_voice):
        return [Event(kind="bar_rest")]
    tuplet_left = 0
    for n in notes:
        if n.grace:
            ev = Event(kind="note", pitches=[_to_concert(part, p) for p in n.pitches],
                       ties=[False] * len(n.pitches))
            base = _TYPE_QUARTERS.get(n.grace_type or "16th", Fraction(1, 4))
            ev.base, ev.dots = base, 0
            graces.append(ev)
            grace_slash = grace_slash or n.grace_slash
            continue
        q = Fraction(n.duration, DIVISIONS)
        if n.tuplet is not None:
            actual, normal = n.tuplet.actual, n.tuplet.normal
            written = q * actual / normal
            code = _code(written) or _nearest_code(written)
            ev = _event_from(part, n, code)
            ev.tuplet = (actual, normal)
            if tuplet_left <= 0 or n.tuplet.start:
                ev.tuplet_start = True
                base = _TYPE_QUARTERS.get(n.tuplet.base_type, code[0])
                tuplet_left = base * actual
            tuplet_left -= written
            if n.tuplet.stop or tuplet_left <= 0:
                ev.tuplet_stop = True
                tuplet_left = 0
            if graces:
                ev.graces, ev.grace_slash = graces, grace_slash
                graces, grace_slash = [], False
            out.append(ev)
            continue
        pieces = _split(q)
        for k, code in enumerate(pieces):
            ev = _event_from(part, n, code, first=(k == 0), last=(k == len(pieces) - 1))
            if k == 0 and graces:
                ev.graces, ev.grace_slash = graces, grace_slash
                graces, grace_slash = [], False
            out.append(ev)
    if out and isinstance(out[-1], Event) and out[-1].tuplet and not out[-1].tuplet_stop:
        out[-1].tuplet_stop = True
    return out


def _event_from(part: Part, n: Note, code, first: bool = True, last: bool = True) -> Event:
    base, dots = code
    if n.is_rest:
        return Event(kind="rest" if n.print_object else "spacer", base=base, dots=dots)
    pitches = [_to_concert(part, p) for p in n.pitches]
    order = sorted(range(len(pitches)), key=lambda k: pitches[k].midi)
    written = [n.pitches[k] for k in order]
    pitches = [pitches[k] for k in order]
    starts = (set(n.tie_start_pitches) if n.tie_start_pitches is not None
              else {p.midi for p in written} if n.tie_start else set())
    ties = [(not last) or (w.midi in starts) for w in written]
    ev = Event(kind="note", pitches=pitches, ties=ties, base=base, dots=dots)
    if first:
        ev.slur_starts = (1 if n.slur_start else 0) + sum(1 for k, _ in n.more_slurs
                                                          if k == "start")
        ev.marks = _marks(n)
        if n.lyric:
            ev.lyric = n.lyric + ("-" if n.lyric_syllabic in ("begin", "middle") else "")
    if last:
        ev.slur_stops = (1 if n.slur_stop else 0) + sum(1 for k, _ in n.more_slurs
                                                        if k == "stop")
    return ev


def _marks(n: Note) -> list[str]:
    out: list[str] = []
    for a in n.articulations:
        name = MARK_NAMES.get(("art", a))
        if name:
            out.append(name)
    for o in n.ornaments:
        name = MARK_NAMES.get(("orn", o))
        if name:
            out.append(name)
    for t in n.technical:
        if t.isdigit() and 1 <= int(t) <= 5:
            out.append(f"f{t}")
        else:
            name = MARK_NAMES.get(("tech", t))
            if name:
                out.append(name)
    if n.tremolo:
        out.append(f"trem{min(3, max(1, n.tremolo))}")
    if n.fermata:
        out.append("fermata")
    if n.arpeggiate:
        out.append("arp")
    return out


def _code(q: Fraction):
    for base in sorted(DURATION_LETTERS.values(), reverse=True):
        total, add = base, base
        for dots in range(0, 3):
            if dots:
                add /= 2
                total += add
            if total == q:
                return (base, dots)
    return None


def _nearest_code(q: Fraction):
    best = min(DURATION_LETTERS.values(), key=lambda b: abs(b - q))
    return (best, 0)


def _split(q: Fraction) -> list[tuple[Fraction, int]]:
    """A duration as one value if possible, else tied values, longest first."""
    c = _code(q)
    if c is not None:
        return [c]
    from .msn import split_quarters
    pieces = split_quarters(q)
    return pieces or [(Fraction(1, 16), 0)]


# ---------------------------------------------------------------------------
def _place_directions(lines: dict[tuple[int, int], VoiceLine], spec: PartSpec, m) -> None:
    """Put each dynamic, hairpin, pedal mark and word into the right voice line."""
    keyboard = spec.staves >= 2
    for d in sorted(m.directions, key=lambda d: d.offset):
        mk = _marking(d)
        if mk is None:
            continue
        staff = max(1, min(spec.staves, d.staff or 1))
        if mk.kind == "pedal" and keyboard:
            staff = spec.staves if spec.staves < 3 else 2
        if mk.kind in ("dynamic", "hairpin", "hairpin_end") and keyboard and staff == 2 \
                and d.placement == "above":
            staff = 1
        vl = lines.get((staff, 1)) or next(iter(lines.values()))
        _insert_marking(vl, mk, Fraction(d.offset, DIVISIONS))


def _marking(d: Direction) -> Marking | None:
    if d.kind == "dynamics":
        return Marking("dynamic", d.value)
    if d.kind == "wedge":
        if d.value in ("crescendo", "diminuendo"):
            return Marking("hairpin", d.value)
        return Marking("hairpin_end")
    if d.kind == "pedal":
        if d.value in ("start", "change", "resume"):
            return Marking("pedal", "down")
        if d.value in ("stop", "discontinue"):
            return Marking("pedal", "up")
        return None
    if d.kind == "words" and d.value.strip():
        return Marking("text", d.value.strip(),
                       placement="above" if d.placement == "above" else "")
    return None


def _insert_marking(vl: VoiceLine, mk: Marking, offset: Fraction) -> None:
    mk.offset = offset
    pos = Fraction(0)
    for i, it in enumerate(vl.items):
        if isinstance(it, Event):
            if it.kind == "bar_rest":
                break
            if pos >= offset:
                vl.items.insert(i, mk)
                return
            pos += it.duration
    if vl.items and isinstance(vl.items[0], Event) and vl.items[0].kind == "bar_rest":
        # A whole-bar rest can't carry a mid-bar marking; write the bar out.
        if offset == 0:
            vl.items.insert(0, mk)
            return
    vl.items.append(mk)
