"""MusicXML 4.0 export.

MuseScore imports MusicXML far more faithfully than a plugin can build a score
through the cursor API, so this is Motif's primary delivery format: slurs,
pedalling, hairpins, tuplets, grace notes and multi-voice piano writing all
survive the trip.
"""
from __future__ import annotations

import re
from xml.sax.saxutils import escape

from ..score import (DIVISIONS, ChordSymbol, Direction, Measure, Note, Part,
                     Score, note_type_and_dots)
from ..theory.pitch import Pitch

_HEADER = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" '
           '"http://www.musicxml.org/dtds/partwise.dtd">\n')

CLEF_MAP = {
    "G": ("G", 2, 0), "treble": ("G", 2, 0),
    "F": ("F", 4, 0), "bass": ("F", 4, 0),
    "C": ("C", 3, 0), "alto": ("C", 3, 0), "tenor": ("C", 4, 0),
    "G8vb": ("G", 2, -1), "treble8vb": ("G", 2, -1),
    "F8vb": ("F", 4, -1), "percussion": ("percussion", 2, 0),
}

_ARTICULATION_GROUP = {
    "staccato": "articulations", "staccatissimo": "articulations",
    "accent": "articulations", "strong-accent": "articulations",
    "tenuto": "articulations", "detached-legato": "articulations",
    "spiccato": "articulations", "breath-mark": "articulations",
    "trill-mark": "ornaments", "turn": "ornaments", "inverted-turn": "ornaments",
    "mordent": "ornaments", "inverted-mordent": "ornaments",
    "tremolo": "ornaments", "schleifer": "ornaments",
    "up-bow": "technical", "down-bow": "technical", "fingering": "technical",
    "harmonic": "technical", "open-string": "technical",
}

DYNAMIC_WORDS = ("pppp", "ppp", "pp", "p", "mp", "mf", "f", "ff", "fff", "ffff",
                 "fp", "sf", "sfz", "sffz", "fz", "rf", "rfz", "sfp")


class MusicXMLWriter:
    def __init__(self, score: Score, *, page_layout: bool = True):
        self.score = score
        self._accidentals: dict | None = None
        self.page_layout = page_layout
        self._out: list[str] = []
        self._indent = 0

    # -- tiny XML helpers -------------------------------------------------
    def _w(self, text: str) -> None:
        self._out.append("  " * self._indent + text)

    def _open(self, tag: str, attrs: str = "") -> None:
        self._w(f"<{tag}{(' ' + attrs) if attrs else ''}>")
        self._indent += 1

    def _close(self, tag: str) -> None:
        self._indent -= 1
        self._w(f"</{tag}>")

    def _leaf(self, tag: str, value=None, attrs: str = "") -> None:
        a = (" " + attrs) if attrs else ""
        if value is None or value == "":
            self._w(f"<{tag}{a}/>")
        else:
            self._w(f"<{tag}{a}>{escape(str(value))}</{tag}>")

    # -- top level --------------------------------------------------------
    def render(self) -> str:
        s = self.score
        self._out = [_HEADER.rstrip("\n")]
        self._open("score-partwise", 'version="4.0"')
        self._work_and_identification()
        if self.page_layout:
            self._defaults()
        self._credits()
        self._part_list()
        for part in s.parts:
            self._part(part)
        self._close("score-partwise")
        return "\n".join(self._out) + "\n"

    def _work_and_identification(self) -> None:
        s = self.score
        self._open("work")
        self._leaf("work-title", s.title)
        self._close("work")
        if s.metadata.get("movement"):
            self._leaf("movement-number", s.metadata["movement"])
        if s.subtitle:
            self._leaf("movement-title", s.subtitle)
        self._open("identification")
        self._leaf("creator", s.composer, 'type="composer"')
        if s.lyricist:
            self._leaf("creator", s.lyricist, 'type="lyricist"')
        self._leaf("rights", s.copyright or "Generated by Motif.ai")
        self._open("encoding")
        self._leaf("software", "Motif.ai")
        # An empty or free-form date makes the whole file fail schema
        # validation, which MuseScore answers with an "import anyway?" prompt.
        date = str(s.metadata.get("date") or "")
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
            self._leaf("encoding-date", date)
        for feature in ("accidental", "beam", "print", "stem"):
            self._leaf("supports", None,
                       f'element="{feature}" type="yes"' if feature != "print"
                       else 'element="print" attribute="new-system" type="yes" value="yes"')
        self._close("encoding")
        # Provenance fields, so a later request can read back exactly what
        # generated this score — its composer, form and forces — instead of
        # having to guess from the notes alone. Every field is optional and
        # a plain miscellaneous-field, so any MusicXML reader (MuseScore
        # included) that does not know about them simply ignores them.
        misc = [
            ("motif-prompt", s.metadata.get("prompt")),
            ("motif-style", s.metadata.get("style")),
            ("motif-form", s.metadata.get("form")),
            ("motif-ensemble", s.metadata.get("ensemble")),
            ("motif-character", s.metadata.get("character")),
            ("motif-seed", s.metadata.get("seed")),
            ("motif-engine", s.metadata.get("engine")),
            ("motif-session", s.metadata.get("session")),
        ]
        misc = [(name, value) for name, value in misc if value not in (None, "")]
        if misc:
            self._open("miscellaneous")
            for name, value in misc:
                self._leaf("miscellaneous-field", value, f'name="{name}"')
            self._close("miscellaneous")
        self._close("identification")

    def _defaults(self) -> None:
        self._open("defaults")
        self._open("scaling")
        self._leaf("millimeters", "7.0")
        self._leaf("tenths", "40")
        self._close("scaling")
        self._open("page-layout")
        self._leaf("page-height", "1683.36")
        self._leaf("page-width", "1190.88")
        for kind in ("even", "odd"):
            self._open("page-margins", f'type="{kind}"')
            for m, v in (("left-margin", "56.6929"), ("right-margin", "56.6929"),
                         ("top-margin", "56.6929"), ("bottom-margin", "113.386")):
                self._leaf(m, v)
            self._close("page-margins")
        self._close("page-layout")
        self._open("word-font")
        self._indent -= 1
        self._out.pop()
        self._w('<word-font font-family="Edwin" font-size="10"/>')
        self._w('<lyric-font font-family="Edwin" font-size="10"/>')
        self._close("defaults")

    def _credits(self) -> None:
        s = self.score
        self._open("credit", 'page="1"')
        self._leaf("credit-type", "title")
        self._w(f'<credit-words default-x="595" default-y="1600" justify="center" '
                f'valign="top" font-size="22">{escape(s.title)}</credit-words>')
        self._close("credit")
        if s.subtitle:
            self._open("credit", 'page="1"')
            self._leaf("credit-type", "subtitle")
            self._w(f'<credit-words default-x="595" default-y="1550" justify="center" '
                    f'valign="top" font-size="14">{escape(s.subtitle)}</credit-words>')
            self._close("credit")
        self._open("credit", 'page="1"')
        self._leaf("credit-type", "composer")
        self._w(f'<credit-words default-x="1134" default-y="1500" justify="right" '
                f'valign="bottom">{escape(s.composer)}</credit-words>')
        self._close("credit")

    def _part_list(self) -> None:
        self._open("part-list")
        grouped = [p for p in self.score.parts]
        if len(grouped) > 1:
            self._open("part-group", 'number="1" type="start"')
            self._leaf("group-symbol", "bracket")
            self._leaf("group-barline", "yes")
            self._close("part-group")
        for p in self.score.parts:
            self._open("score-part", f'id="{p.id}"')
            self._leaf("part-name", p.name)
            self._leaf("part-abbreviation", p.abbreviation)
            self._open("score-instrument", f'id="{p.id}-I1"')
            self._leaf("instrument-name", p.name)
            self._leaf("instrument-sound",
                       p.instrument_sound or _instrument_sound(p.midi_program))
            self._close("score-instrument")
            self._w(f'<midi-device id="{p.id}-I1" port="1"></midi-device>')
            self._open("midi-instrument", f'id="{p.id}-I1"')
            self._leaf("midi-channel", p.midi_channel)
            self._leaf("midi-program", p.midi_program + 1)
            self._leaf("volume", f"{p.volume:.1f}")
            self._leaf("pan", f"{p.pan:.1f}")
            self._close("midi-instrument")
            self._close("score-part")
        if len(grouped) > 1:
            self._w('<part-group number="1" type="stop"/>')
        self._close("part-list")

    # -- parts ------------------------------------------------------------
    def _part(self, part: Part) -> None:
        self._open("part", f'id="{part.id}"')
        current_time = self.score.time
        current_key = self.score.key
        for idx, m in enumerate(part.measures):
            if m.time:
                current_time = m.time
            if m.key is not None:
                current_key = m.key
            self._accidentals = _accidentals(m, current_key)
            self._measure(part, m, idx, current_time)
        self._close("part")

    def _measure(self, part: Part, m: Measure, idx: int, current_time) -> None:
        attrs = f'number="{m.number}"'
        if m.implicit:
            attrs += ' implicit="yes"'
        if m.width:
            attrs += f' width="{m.width:.2f}"'
        self._open("measure", attrs)

        first = idx == 0
        if m.repeat_start or (m.ending and m.ending_type in ("start", "both", "")):
            self._open("barline", 'location="left"')
            if m.repeat_start:
                self._leaf("bar-style", "heavy-light")
            if m.ending and m.ending_type in ("start", "both", ""):
                self._w(f'<ending number="{m.ending}" type="start">{m.ending}.</ending>')
            if m.repeat_start:
                self._w('<repeat direction="forward"/>')
            self._close("barline")

        self._attributes(part, m, first, current_time)

        # Tempo belongs to the whole score; MusicXML puts it in the top part.
        is_top = part is self.score.parts[0]
        tempos = [t for t in self.score.tempos if t.measure == m.number] if is_top else []
        early = [d for d in m.directions if d.offset == 0]
        for t in [t for t in tempos if t.offset == 0]:
            self._tempo_direction(t, part)
        for d in sorted(early, key=_direction_order):
            self._direction(d, part)

        staff_voices = _voices_by_staff(part, m)
        pos = 0
        for si, (staff, voices) in enumerate(staff_voices):
            for vi, voice in enumerate(voices):
                notes = m.voices.get(voice, [])
                if (si or vi) and pos > 0:
                    self._open("backup")
                    self._leaf("duration", pos)
                    self._close("backup")
                    pos = 0
                pos = self._emit_voice(part, m, notes, voice, staff, pos)

        pending = [(d.offset, 1, d) for d in m.directions if d.offset > 0]
        pending += [(t.offset, 0, t) for t in tempos if t.offset > 0]
        if pending:
            # Rewind, then step forward to each marking so it lands in time.
            if pos > 0:
                self._open("backup")
                self._leaf("duration", pos)
                self._close("backup")
            at = 0
            for offset, _, item in sorted(pending, key=lambda x: (x[0], x[1])):
                if offset > at:
                    self._open("forward")
                    self._leaf("duration", offset - at)
                    self._close("forward")
                    at = offset
                if isinstance(item, Direction):
                    self._direction(item, part)
                else:
                    self._tempo_direction(item, part)

        ends_volta = m.ending and m.ending_type in ("stop", "both", "")
        if m.repeat_end or m.barline or ends_volta:
            self._open("barline", 'location="right"')
            if m.repeat_end:
                self._leaf("bar-style", "light-heavy")
            elif m.barline:
                self._leaf("bar-style", m.barline)
            if ends_volta:
                kind = "stop" if m.repeat_end else "discontinue"
                self._w(f'<ending number="{m.ending}" type="{kind}"/>')
            if m.repeat_end:
                self._w('<repeat direction="backward"/>')
            self._close("barline")
        self._close("measure")

    def _attributes(self, part: Part, m: Measure, first: bool, current_time) -> None:
        needs = first or m.key is not None or m.time is not None or m.clefs
        if not needs:
            return
        self._open("attributes")
        if first:
            self._leaf("divisions", DIVISIONS)
        key = m.key or (self.score.key if first else None)
        if key is not None:
            self._open("key")
            self._leaf("fifths", key.fifths)
            self._leaf("mode", "minor" if key.is_minor else "major")
            self._close("key")
        time = m.time or (self.score.time if first else None)
        if time is not None:
            symbol = ""
            self._open("time", symbol)
            self._leaf("beats", time[0])
            self._leaf("beat-type", time[1])
            self._close("time")
        if first and part.staves > 1:
            self._leaf("staves", part.staves)
        clefs = m.clefs or (part.clefs if first else None)
        if clefs:
            for staff, name in sorted(clefs.items()):
                sign, line, octv = CLEF_MAP.get(name, ("G", 2, 0))
                attrs = f'number="{staff}"' if part.staves > 1 else ""
                self._open("clef", attrs)
                self._leaf("sign", sign)
                self._leaf("line", line)
                if octv:
                    self._leaf("clef-octave-change", octv)
                self._close("clef")
        if first and part.transpose:
            diatonic, chromatic, octave = part.transpose
            self._open("transpose")
            self._leaf("diatonic", diatonic)
            self._leaf("chromatic", chromatic)
            if octave:
                self._leaf("octave-change", octave)
            self._close("transpose")
        self._close("attributes")

    def _tempo_direction(self, t, part: Part) -> None:
        playback = t.quarter_bpm if hasattr(t, "quarter_bpm") else t.bpm
        if not getattr(t, "visible", True):
            # Playback only: MuseScore turns a bare <sound tempo> into an
            # invisible tempo change, which is how rit. and accel. are heard.
            self._leaf("sound", None, f'tempo="{playback:.2f}"')
            return
        self._open("direction", 'placement="above"')
        if t.text:
            self._open("direction-type")
            self._w(f'<words font-weight="bold" font-size="12">{escape(t.text)}</words>')
            # The unbolded space MuseScore itself writes between a tempo word
            # and its metronome mark; without it MuseScore 3 runs them together.
            self._w('<words font-weight="normal"> </words>')
            self._close("direction-type")
        self._open("direction-type")
        self._open("metronome", 'parentheses="no"')
        self._leaf("beat-unit", t.beat_unit)
        if t.dotted:
            self._leaf("beat-unit-dot", None)
        self._leaf("per-minute", _bpm_text(t.bpm))
        self._close("metronome")
        self._close("direction-type")
        if part.staves > 1:
            self._leaf("staff", 1)
        self._leaf("sound", None, f'tempo="{playback:.2f}"')
        self._close("direction")

    def _direction(self, d: Direction, part: Part | None = None) -> None:
        part = part or (self.score.parts[0] if self.score.parts else None)
        placement = f'placement="{d.placement}"' if d.placement else ""
        self._open("direction", placement)
        self._open("direction-type")
        if d.kind == "dynamics":
            self._open("dynamics")
            v = d.value if d.value in DYNAMIC_WORDS else "mf"
            self._leaf(v, None)
            self._close("dynamics")
        elif d.kind == "wedge":
            typ = d.value  # "crescendo" | "diminuendo" | "stop"
            n = d.extra.get("number", 1)
            self._w(f'<wedge type="{typ}" number="{n}"/>')
        elif d.kind == "pedal":
            typ = d.value  # start | stop | change
            line = "yes" if d.extra.get("line", True) else "no"
            sign = "yes" if d.extra.get("sign", True) else "no"
            self._w(f'<pedal type="{typ}" line="{line}" sign="{sign}"/>')
        elif d.kind == "octave-shift":
            n = d.extra.get("number", 1)
            size = d.extra.get("size", 8)
            self._w(f'<octave-shift type="{d.value}" size="{size}" number="{n}"/>')
        elif d.kind == "rehearsal":
            self._w(f'<rehearsal font-weight="bold" enclosure="square">'
                    f'{escape(d.value)}</rehearsal>')
        elif d.kind == "segno":
            self._leaf("segno", None)
        elif d.kind == "coda":
            self._leaf("coda", None)
        elif d.kind == "bracket":
            n = d.extra.get("number", 1)
            self._w(f'<bracket type="{d.value}" number="{n}" line-end="none"/>')
        else:  # words
            style = d.extra.get("style", "italic")
            weight = d.extra.get("weight", "")
            size = d.extra.get("size", 11)
            attrs = f'font-style="{style}" font-size="{size}"'
            if weight:
                attrs += f' font-weight="{weight}"'
            self._w(f"<words {attrs}>{escape(d.value)}</words>")
        self._close("direction-type")
        if part is not None and part.staves > 1:
            self._leaf("staff", d.staff)
        if d.extra.get("dynamics_velocity"):
            self._leaf("sound", None, f'dynamics="{d.extra["dynamics_velocity"]}"')
        elif d.extra.get("tempo"):
            self._leaf("sound", None, f'tempo="{d.extra["tempo"]}"')
        self._close("direction")

    # -- notes ------------------------------------------------------------
    def _emit_voice(self, part: Part, m: Measure, notes: list[Note], voice: int,
                    staff: int, pos: int) -> int:
        multi_staff = part.staves > 1
        inline = sorted([d for d in m.directions
                         if d.offset > 0 and d.extra.get("inline") and d.voice == voice],
                        key=lambda d: d.offset)
        for n in notes:
            while inline and inline[0].offset <= pos:
                self._direction(inline.pop(0), part)
            if n.chord_symbol:
                self._harmony(n.chord_symbol)
            self._note(n, multi_staff, staff)
            if not n.grace:
                pos += n.duration
        for d in inline:
            self._direction(d, part)
        return pos

    def _harmony(self, cs: ChordSymbol) -> None:
        self._open("harmony", 'print-frame="no"')
        self._open("root")
        self._leaf("root-step", cs.root.step)
        if cs.root.alter:
            self._leaf("root-alter", cs.root.alter)
        self._close("root")
        attrs = f'text="{escape(cs.text)}"' if cs.text else ""
        self._leaf("kind", cs.kind, attrs)
        if cs.bass is not None:
            self._open("bass")
            self._leaf("bass-step", cs.bass.step)
            if cs.bass.alter:
                self._leaf("bass-alter", cs.bass.alter)
            self._close("bass")
        self._close("harmony")

    def _note(self, n: Note, multi_staff: bool, staff: int) -> None:
        # MusicXML carries playback nuance on the note itself, as a percentage
        # where 100 is a forte. Writing it preserves the shaping that makes the
        # music sound played rather than printed.
        base_attrs = []
        if n.pitches and not n.grace:
            pct = max(1, min(400, round(n.velocity / 0.90)))
            base_attrs.append(f'dynamics="{pct}"')
        if not n.print_object:
            base_attrs.append('print-object="no"')
        attrs = " ".join(base_attrs)
        tie_starts = set(n.tie_start_pitches) if n.tie_start_pitches is not None else None
        tie_stops = set(n.tie_stop_pitches) if n.tie_stop_pitches is not None else None
        for i, p in enumerate(n.pitches or [None]):
            self._open("note", attrs if i == 0 else
                       ('print-object="no"' if not n.print_object else ""))
            if n.grace:
                self._w('<grace slash="yes"/>' if n.grace_slash else '<grace/>')
            if n.cue and not n.grace:
                self._leaf("cue", None)
            if i > 0:
                self._leaf("chord", None)
            if p is None:
                self._leaf("rest", None, 'measure="yes"' if n.measure_rest else "")
            else:
                self._open("pitch")
                self._leaf("step", p.step)
                if p.alter:
                    self._leaf("alter", p.alter)
                self._leaf("octave", p.octave)
                self._close("pitch")
            if not n.grace:
                self._leaf("duration", max(1, n.duration))
            stop_here = n.tie_stop and p is not None and (tie_stops is None or p.midi in tie_stops)
            start_here = n.tie_start and p is not None and (tie_starts is None or p.midi in tie_starts)
            if stop_here:
                self._w('<tie type="stop"/>')
            if start_here:
                self._w('<tie type="start"/>')
            self._leaf("voice", n.voice)
            if not (p is None and n.measure_rest):
                ntype, dots = note_type_and_dots(
                    _tuplet_display(n.duration, n.tuplet) if n.tuplet else n.duration)
                if n.grace:
                    ntype, dots = (n.grace_type or n.__dict__.get("grace_type") or "16th"), 0
                self._leaf("type", ntype)
                for _ in range(dots):
                    self._leaf("dot", None)
            if p is not None:
                shown = self._accidentals.get((id(n), i), None) \
                    if self._accidentals is not None else (
                        p.accidental_name if _needs_accidental(p) else None)
                if shown:
                    self._leaf("accidental", shown)
            if n.tuplet:
                self._open("time-modification")
                self._leaf("actual-notes", n.tuplet.actual)
                self._leaf("normal-notes", n.tuplet.normal)
                self._close("time-modification")
            if n.stem and p is not None:
                self._leaf("stem", n.stem)
            if multi_staff:
                self._leaf("staff", staff)
            # A beam belongs to the chord, not to each notehead in it: it is
            # written once, on the note that starts the chord. Repeating it on
            # every <chord/> note makes readers reject the chord outright.
            if i == 0:
                for level, kind in enumerate(n.beam, start=1):
                    self._leaf("beam", kind, f'number="{level}"')
            self._notations(n, first_notehead=(i == 0), tie_stop=stop_here,
                            tie_start=start_here)
            if i == 0 and n.lyric and p is not None:
                self._open("lyric", 'number="1"')
                self._leaf("syllabic", n.lyric_syllabic or "single")
                self._leaf("text", n.lyric)
                self._close("lyric")
            self._close("note")

    def _notations(self, n: Note, first_notehead: bool, tie_stop: bool | None = None,
                   tie_start: bool | None = None) -> None:
        tie_stop = n.tie_stop if tie_stop is None else tie_stop
        tie_start = n.tie_start if tie_start is None else tie_start
        has = (tie_start or tie_stop or n.slur_start or n.slur_stop or n.more_slurs
               or n.articulations or n.ornaments or n.technical or n.tuplet
               or n.fermata or n.arpeggiate or n.notations_text or n.tremolo)
        if not has:
            return
        if not first_notehead and not (tie_start or tie_stop or n.arpeggiate):
            return
        self._open("notations")
        if tie_stop:
            self._w('<tied type="stop"/>')
        if tie_start:
            self._w('<tied type="start"/>')
        if first_notehead:
            if n.slur_stop:
                self._w(f'<slur type="stop" number="{n.slur_stop}"/>')
            for kind, number in n.more_slurs:
                if kind == "stop":
                    self._w(f'<slur type="stop" number="{number}"/>')
            if n.slur_start:
                self._w(f'<slur type="start" number="{n.slur_start}" placement="above"/>')
            for kind, number in n.more_slurs:
                if kind == "start":
                    self._w(f'<slur type="start" number="{number}" placement="above"/>')
            if n.tuplet and (n.tuplet.start or n.tuplet.stop):
                if n.tuplet.start:
                    self._w(f'<tuplet type="start" number="{n.tuplet.number}" '
                            f'bracket="{"no" if n.beam else "yes"}" show-number="actual"/>')
                if n.tuplet.stop:
                    self._w(f'<tuplet type="stop" number="{n.tuplet.number}"/>')
            arts = [a for a in n.articulations if _ARTICULATION_GROUP.get(a) == "articulations"]
            if arts:
                self._open("articulations")
                for a in arts:
                    self._leaf(a, None)
                self._close("articulations")
            orns = [a for a in n.ornaments if _ARTICULATION_GROUP.get(a) == "ornaments"]
            if orns or n.tremolo:
                self._open("ornaments")
                for a in orns:
                    self._leaf(a, None)
                if n.tremolo:
                    self._leaf("tremolo", n.tremolo, 'type="single"')
                self._close("ornaments")
            if n.technical:
                self._open("technical")
                for t in n.technical:
                    if t.isdigit():
                        self._leaf("fingering", t)
                    else:
                        self._leaf(t, None)
                self._close("technical")
            if n.fermata:
                self._leaf("fermata", "normal", 'type="upright"')
        if n.arpeggiate:
            self._leaf("arpeggiate", None)
        self._close("notations")


def _direction_order(d: Direction) -> int:
    return {"rehearsal": 0, "words": 1, "dynamics": 2, "wedge": 3, "pedal": 4}.get(d.kind, 5)


def _bpm_text(bpm: float) -> str:
    return str(int(round(bpm))) if abs(bpm - round(bpm)) < 0.05 else f"{bpm:.1f}"


def _tuplet_display(duration: int, t) -> int:
    """The *written* value of a tuplet note, which differs from its real length."""
    return int(round(duration * t.actual / t.normal))


_ACC_NAME = {-2: "flat-flat", -1: "flat", 0: "natural", 1: "sharp", 2: "double-sharp"}


def _accidentals(m: Measure, key) -> dict:
    """Which noteheads need a printed accidental, as an engraver decides it.

    The key signature sets each letter's alteration; an accidental holds for
    the rest of the bar on that line and octave; a tied continuation shows
    none. Naturals are printed where they cancel something, and nowhere else.
    """
    sig = key.signature_alters if key is not None else {}
    out: dict = {}
    by_staff: dict[int, list[tuple[int, int, int, Note]]] = {}
    for voice, notes in m.voices.items():
        t = 0
        for order, n in enumerate(notes):
            if not n.pitches:
                t += 0 if n.grace else n.duration
                continue
            # Grace notes sound just before their beat.
            by_staff.setdefault(n.staff, []).append((t, 0 if n.grace else 1, order, n))
            if not n.grace:
                t += n.duration
    for staff, items in by_staff.items():
        state: dict[tuple[str, int], int] = {}
        for t, _, _, n in sorted(items, key=lambda x: (x[0], x[1], x[2])):
            tied_in = set(n.tie_stop_pitches) if n.tie_stop_pitches is not None else (
                {p.midi for p in n.pitches} if n.tie_stop else set())
            for i, p in enumerate(n.pitches):
                slot = (p.step, p.octave)
                current = state.get(slot, sig.get(p.step, 0))
                if p.midi in tied_in and n.tie_stop:
                    continue
                if p.alter != current:
                    out[(id(n), i)] = _ACC_NAME.get(p.alter, "natural")
                    state[slot] = p.alter
    return out


def _needs_accidental(p: Pitch) -> bool:
    # MuseScore recomputes courtesy accidentals; emitting them for every altered
    # note is safe and avoids missing ones on chromatic passages.
    return p.alter != 0


def _voices_by_staff(part: Part, m: Measure) -> list[tuple[int, list[int]]]:
    by_staff: dict[int, set[int]] = {}
    for v, notes in m.voices.items():
        if not notes:
            continue
        staff = notes[0].staff
        by_staff.setdefault(staff, set()).add(v)
    if not by_staff:
        by_staff = {1: {1}}
    return [(s, sorted(vs)) for s, vs in sorted(by_staff.items())]


def _instrument_sound(program: int) -> str:
    table = {0: "keyboard.piano", 6: "keyboard.harpsichord", 19: "keyboard.organ",
             40: "strings.violin", 41: "strings.viola", 42: "strings.cello",
             43: "strings.contrabass", 48: "strings.group", 49: "strings.group",
             56: "brass.trumpet", 57: "brass.trombone", 60: "brass.french-horn",
             68: "wind.reed.oboe", 71: "wind.reed.clarinet", 70: "wind.reed.bassoon",
             73: "wind.flutes.flute", 45: "strings.violin", 46: "pluck.harp",
             47: "drum.timpani", 52: "voice.aa"}
    return table.get(program, "keyboard.piano")


def to_musicxml(score: Score, **kw) -> str:
    return MusicXMLWriter(score, **kw).render()
