"""The composer: turns a CompositionPlan into a fully engraved Score."""
from __future__ import annotations

import random
from dataclasses import replace

from ..engrave.beaming import apply_beams
from ..engrave.layout import fill_empty_measures, merge_tied_rests, place_direction, place_voice
from ..plan import CompositionPlan, InstrumentPlan, SectionPlan
from ..score import (DIVISIONS, Direction, EIGHTH, HALF, Note, Part, QUARTER, Score,
                     SIXTEENTH, TempoMark, bar_duration, beat_duration)
from ..theory.harmony import Chord, roman_to_chord
from ..theory.pitch import Key, Pitch
from .harmony_timeline import HarmonyTimeline
from .material import CONTOUR_BY_NAME, Motif, develop, generate_motif
from .melody import MelodyWriter, flatten_rhythm, metric_strength
from .progression import build_progression, chord_durations
from .rhythm import RhythmGenerator
from .expression import (DYN_VELOCITY, ExpressionPlanner, Phrase,
                         detect_phrases, shift_dynamic)
from .styles import StyleProfile, resolve_style
from .textures import TextureContext, render_texture
from .voicing import spell_in_chord

DYN_SCALE = ["ppp", "pp", "p", "mp", "mf", "f", "ff", "fff"]

#: What to tell the musician while a section is being written — plain
#: language, never the internal role name.
_SECTION_PROGRESS = {
    "intro": "Writing the opening…",
    "theme": "Stating the theme…",
    "transition": "Building a bridge to what's next…",
    "development": "Developing the material…",
    "recap": "Bringing the theme back…",
    "cadenza": "Writing a cadenza…",
    "coda": "Bringing it home…",
}


class Composer:
    def __init__(self, plan: CompositionPlan, model=None, progress=None):
        self.plan = plan
        self.style: StyleProfile = resolve_style(plan.style)
        self.key = Key.parse(plan.key)
        self.time = tuple(plan.time)
        self.rng = random.Random(plan.seed or 0)
        self.model = model
        self._progress = progress
        self.bar_ticks = bar_duration(self.time)
        self.beat_ticks = beat_duration(self.time)
        self._slur_id = 1
        self._wedge_id = 1
        self.expression = ExpressionPlanner(self.rng, self.style, float(plan.tempo))
        self._section_starts: list[int] = []
        self._phrases: list[Phrase] = []

    def _report(self, text: str) -> None:
        if self._progress is not None:
            try:
                self._progress(text)
            except Exception:
                pass          # a broken status display must never break composing

    # ------------------------------------------------------------------
    def render(self) -> Score:
        p = self.plan
        self._report("Sketching the opening idea…")
        score = Score(title=p.title, subtitle=p.subtitle, key=self.key, time=self.time,
                      tempo=p.tempo, composer="Generated by Motif.ai")
        score.metadata.update({"prompt": p.prompt, "style": self.style.name,
                               "form": p.form, "seed": p.seed,
                               "character": p.character, "ensemble": p.ensemble})
        instruments = p.instruments or [InstrumentPlan()]
        parts = [self._make_part(i, ip) for i, ip in enumerate(instruments)]
        for part in parts:
            score.add_part(part)

        opening = p.tempo_text or self._tempo_word()

        motif = self._seed_motif()
        bar_cursor = 0
        prev_key = self.key
        last_melody_pitch: Pitch | None = None

        for si, sec in enumerate(p.sections):
            self._report(_SECTION_PROGRESS.get(sec.role, "Writing the {label}…")
                        .format(label=sec.label))
            sec_key = sec.resolved_key()
            sec_time = tuple(sec.time) if sec.time else self.time
            bar_ticks = bar_duration(sec_time)
            beat_ticks = beat_duration(sec_time)
            start_tick = bar_cursor * self.bar_ticks

            timeline, chords = self._section_harmony(sec, sec_key, start_tick,
                                                     bar_ticks, sec_time)
            sec_motif = self._transform_motif(motif, sec, si)
            melody, last_melody_pitch = self._section_melody(
                sec, sec_key, timeline, sec_motif, bar_ticks, beat_ticks,
                last_melody_pitch)

            self._section_starts.append(bar_cursor)
            self._write_section(score, parts, sec, sec_key, timeline, melody,
                                start_tick, bar_ticks, beat_ticks, si,
                                changed_key=(str(sec_key) != str(prev_key)) or si == 0,
                                changed_time=(sec_time != self.time and sec.time is not None))
            bar_cursor += sec.bars
            prev_key = sec_key

        score.tempos = self.expression.tempo_marks(p.sections, self._section_starts,
                                                   self.bar_ticks)
        if score.tempos:
            score.tempos[0].text = opening or score.tempos[0].text
        self._report("Voicing and engraving the score…")
        self._finalise(score, parts, bar_cursor)
        return score

    # ------------------------------------------------------------------
    def _make_part(self, index: int, ip: InstrumentPlan) -> Part:
        clefs = {i + 1: c for i, c in enumerate(ip.clefs or ["G"])}
        return Part(id=f"P{index+1}", name=ip.name, abbreviation=ip.abbreviation,
                    midi_program=ip.midi_program, midi_channel=min(16, index + 1),
                    staves=max(1, ip.staves), clefs=clefs)

    def _tempo_word(self) -> str:
        return self.rng.choice(self.style.tempo_terms) if self.style.tempo_terms else ""

    def _seed_motif(self) -> Motif:
        """The cell the whole piece is built from.

        When a trained model is loaded it proposes this cell, which gives the
        piece a learned melodic voice; the symbolic engine still owns harmony,
        form and engraving, so a rough proposal cannot derail the structure.
        """
        lo, hi = self.style.motif_length
        n = self.rng.randint(lo, hi)
        rg = RhythmGenerator(self.rng, self.style.name, self.time, self.style.rhythm_density)
        rhythm = rg.bar()[:n]
        while len(rhythm) < n:
            rhythm.append(EIGHTH)

        if self.model is not None:
            neural = self._motif_from_model(n)
            if neural is not None:
                return neural
        return generate_motif(self.rng, length=n, rhythm=rhythm,
                              style=self.style.name, energy=0.5)

    def _motif_from_model(self, length: int) -> Motif | None:
        """Extract a motif from a short neural sample, or None on any failure."""
        try:
            notes = self.model.melody(style=self.style.name, key=self.key,
                                      time=self.time, bars=4,
                                      tempo=float(self.plan.tempo),
                                      seed=self.plan.seed or None)
        except Exception:
            return None
        pitched = [n for n in notes if n.pitches][:length + 1]
        if len(pitched) < 3:
            return None
        steps: list[int] = []
        for a, b in zip(pitched, pitched[1:]):
            # Measure the move in letter-names so the cell stays transposable.
            steps.append(max(-7, min(7, b.pitches[0].diatonic - a.pitches[0].diatonic)))
        rhythm = [n.duration for n in pitched]
        if not steps or all(s == 0 for s in steps):
            return None
        return Motif(steps=steps, rhythm=rhythm, name="n")

    def _transform_motif(self, motif: Motif, sec: SectionPlan, index: int) -> Motif:
        op = sec.motif_op
        if op == "state" or index == 0:
            return motif
        if op == "recall":
            return motif
        if op == "invert":
            return motif.invert()
        if op == "sequence":
            return motif.transpose(self.rng.choice([-1, 1, 2, -2]))
        if op == "fragment":
            return motif.fragment(0, max(2, motif.length - 1))
        if op == "augment":
            return motif.augment(2.0)
        return develop(motif, self.rng, sec.energy, self.style.name)

    # ------------------------------------------------------------------
    def _section_harmony(self, sec: SectionPlan, key: Key, start_tick: int,
                         bar_ticks: int, time) -> tuple[HarmonyTimeline, list[Chord]]:
        beats_per_bar = bar_ticks / DIVISIONS
        total_beats = sec.bars * beats_per_bar
        durs = chord_durations(total_beats, self.style, self.rng, beats_per_bar,
                               sec.harmonic_rhythm)
        romans = build_progression(key, self.style, self.rng, chords_needed=len(durs),
                                   energy=sec.energy, cadence=sec.cadence,
                                   role=sec.role, explicit=sec.progression or None)
        chords = [roman_to_chord(r, key).with_duration(d) for r, d in zip(romans, durs)]
        return HarmonyTimeline(chords, start_tick), chords

    def _section_melody(self, sec: SectionPlan, key: Key, timeline: HarmonyTimeline,
                        motif: Motif, bar_ticks: int, beat_ticks: int,
                        prev_pitch: Pitch | None) -> tuple[list[Note], Pitch | None]:
        style = self.style.with_energy(sec.energy)
        rg = RhythmGenerator(self.rng, self.style.name,
                             (int(bar_ticks / beat_ticks * (beat_ticks / QUARTER) *
                                  4 / 4) or 4, 4), style.rhythm_density)
        rg.time = self.time if sec.time is None else tuple(sec.time)
        bars = rg.phrase(sec.bars, cadence_bar=True)
        rhythm = flatten_rhythm(bars, timeline.start)

        ms = replace(style.melody, colours=self.style.scale_colours,
                     colour_rate=self.style.colour_rate)
        shift = sec.register * 12
        ms.range_low = max(21, ms.range_low + shift)
        ms.range_high = min(108, ms.range_high + shift)

        writer = MelodyWriter(self.rng, key, ms)
        writer.recolour()
        contour_name = ("rising" if sec.role in ("transition", "cadenza")
                        else "descending" if sec.role == "coda"
                        else "wave" if sec.energy > 0.75 else "arch")
        contour = CONTOUR_BY_NAME[contour_name](0.7 + sec.energy * 0.8)

        center = (ms.range_low + ms.range_high) // 2 + int(sec.energy * 4)
        cadence_pitch = self._cadence_pitch(key, ms)

        notes = writer.write(timeline, rhythm, contour, center=center,
                             amplitude=5.0 + sec.energy * 5.0,
                             bar_ticks=bar_ticks, beat_ticks=beat_ticks,
                             motif=motif, motif_op=sec.motif_op,
                             start_pitch=prev_pitch, cadence_pitch=cadence_pitch)
        self._apply_surface(notes, rhythm, sec, key, bar_ticks, beat_ticks)
        return notes, (notes[-1].pitches[0] if notes and notes[-1].pitches else prev_pitch)

    def _cadence_pitch(self, key: Key, ms) -> Pitch | None:
        """Land the phrase on a stable degree in a comfortable register."""
        deg = self.rng.choice([1, 1, 1, 3, 5])
        center = (ms.range_low + ms.range_high) // 2
        best = None
        for octv in range(2, 8):
            p = key.degree_pitch(deg, octv)
            if ms.range_low <= p.midi <= ms.range_high:
                if best is None or abs(p.midi - center) < abs(best.midi - center):
                    best = p
        return best

    # ------------------------------------------------------------------
    def _apply_surface(self, notes: list[Note], rhythm: list[tuple[int, int, object]],
                       sec: SectionPlan, key: Key, bar_ticks: int,
                       beat_ticks: int) -> None:
        """Slurs, articulations, ornaments and grace notes on the melody."""
        st = self.style
        slur_open = False
        run = 0
        for i, n in enumerate(notes):
            tick = rhythm[i][0] if i < len(rhythm) else 0
            strength = metric_strength(tick, bar_ticks, beat_ticks)
            is_last = i == len(notes) - 1

            # Phrase slurs over legato groups.
            if not slur_open and not is_last and (tick % bar_ticks == 0 or run == 0):
                n.slur_start = self._slur_id
                slur_open = True
                run = 0
            run += 1
            if slur_open and (run >= self.rng.randint(3, 7) or is_last
                              or (tick + n.duration) % (bar_ticks * 2) == 0):
                n.slur_stop = self._slur_id
                self._slur_id = self._slur_id % 6 + 1
                slur_open = False

            if self.rng.random() < st.articulation_rate:
                if strength >= 2 and self.rng.random() < 0.4:
                    n.articulations.append("accent" if sec.energy > 0.6 else "tenuto")
                elif n.duration <= EIGHTH and self.rng.random() < 0.5:
                    n.articulations.append("staccato")
            if st.ornaments and self.rng.random() < st.ornament_rate and n.duration >= QUARTER:
                n.ornaments.append(self.rng.choice(list(st.ornaments)))
            if is_last and sec.role in ("coda",):
                n.fermata = True
        if slur_open and notes:
            notes[-1].slur_stop = self._slur_id
        self._add_grace_notes(notes, key)

    def _add_grace_notes(self, notes: list[Note], key: Key) -> None:
        rate = self.style.grace_rate
        if rate <= 0:
            return
        out: list[Note] = []
        for n in notes:
            if (n.pitches and n.duration >= QUARTER and n.tuplet is None
                    and self.rng.random() < rate):
                p = n.pitches[0]
                up = self.rng.random() < 0.55
                g = p.transpose_diatonic(1 if up else -1, key)
                gn = Note([g], SIXTEENTH, grace=True, grace_slash=True,
                          velocity=max(30, n.velocity - 12))
                gn.__dict__["grace_type"] = "16th"
                out.append(gn)
            out.append(n)
        notes[:] = out

    # ------------------------------------------------------------------
    def _write_section(self, score: Score, parts: list[Part], sec: SectionPlan,
                       key: Key, timeline: HarmonyTimeline, melody: list[Note],
                       start_tick: int, bar_ticks: int, beat_ticks: int,
                       index: int, changed_key: bool, changed_time: bool) -> None:
        main = parts[0]
        ensemble = len(parts) > 1
        # Sustain-pedal markings only make sense for a solo keyboard part —
        # checked structurally (one part, piano's own GM program) rather than
        # by an ensemble label, so a continuation whose instrumentation was
        # rebuilt from an existing score still gets pedalling right.
        is_solo_piano = not ensemble and main.midi_program == 0

        if ensemble:
            self._write_ensemble(score, parts, sec, key, timeline, melody,
                                 start_tick, bar_ticks, beat_ticks)
        else:
            self._write_piano(main, sec, key, timeline, melody, start_tick,
                              bar_ticks, beat_ticks)

        # Section head markings on the top part.
        m_index = start_tick // self.bar_ticks + 1
        m = main.measure(m_index)
        if changed_key:
            m.key = key
        if changed_time:
            m.time = tuple(sec.time)
        if index > 0:
            m.directions.append(Direction("rehearsal", sec.label, 0, 1, "above"))
        if sec.text:
            m.directions.append(Direction("words", sec.text, 0, 1, "above",
                                          extra={"style": "italic"}))
        if sec.tempo_scale != 1.0:
            score.tempos.append(TempoMark(m_index, self.plan.tempo * sec.tempo_scale,
                                          text="poco rit." if sec.tempo_scale < 1
                                          else "poco accel."))
        self._write_dynamics(parts, sec, start_tick, bar_ticks)
        if self.style.pedal != "none" and is_solo_piano:
            self._write_pedal(main, timeline, start_tick, bar_ticks)

    def _write_piano(self, part: Part, sec: SectionPlan, key: Key,
                     timeline: HarmonyTimeline, melody: list[Note],
                     start_tick: int, bar_ticks: int, beat_ticks: int) -> None:
        rh = self._right_hand(sec, key, timeline, melody, bar_ticks, beat_ticks)
        self._phrases = detect_phrases(rh, start_tick, bar_ticks, sec.bars, sec.energy)
        # The melody is voiced slightly forward of the accompaniment, which is
        # what a pianist does with the balance between the hands.
        self.expression.shape(rh, self._phrases, start_tick, bar_ticks=bar_ticks,
                              beat_ticks=beat_ticks, base=sec.dynamic or "mf",
                              melody=True, lead_offset=5)
        place_voice(part, rh, start_tick=start_tick, bar_ticks=self.bar_ticks,
                    beat_ticks=beat_ticks, voice=1, staff=1)

        ctx = TextureContext(
            timeline, key, self.rng, bar_ticks=bar_ticks, beat_ticks=beat_ticks,
            low=self.style.lh_range[0], high=self.style.lh_range[1], staff=2, voice=5,
            density=self.style.rhythm_density * (0.7 + sec.energy * 0.6),
            style=self.style.name, dynamic=_dyn_level(sec.dynamic),
            hand_span=self.style.hand_span, pedal=self.style.pedal != "none",
            variety=self._variety(sec))
        lh = render_texture(sec.texture_lh, ctx)
        self.expression.shape(lh, self._phrases, start_tick, bar_ticks=bar_ticks,
                              beat_ticks=beat_ticks, base=sec.dynamic or "mf",
                              melody=False, lead_offset=-15)
        place_voice(part, lh, start_tick=start_tick, bar_ticks=self.bar_ticks,
                    beat_ticks=beat_ticks, voice=5, staff=2)

        if self.style.inner_voice and sec.energy > 0.5 and self.rng.random() < 0.5:
            ictx = replace(ctx, staff=1, voice=2,
                           low=max(48, self.style.lh_range[1] - 4),
                           high=min(76, self.style.rh_range[0] + 10), density=0.3)
            inner = render_texture("sustained", ictx)
            self.expression.shape(inner, self._phrases, start_tick, bar_ticks=bar_ticks,
                                  beat_ticks=beat_ticks, base=sec.dynamic or "mf",
                                  melody=False, lead_offset=-22)
            place_voice(part, inner, start_tick=start_tick, bar_ticks=self.bar_ticks,
                        beat_ticks=beat_ticks, voice=2, staff=1)

    def _variety(self, sec: SectionPlan) -> float:
        """How freely the accompaniment may vary its rhythm from bar to bar.

        Baroque figuration is deliberately even; Romantic writing is not, and a
        long section needs more variation than a short one to stay alive.
        """
        base = {"baroque": 0.22, "classical": 0.45, "romantic": 0.7,
                "late_romantic": 0.75, "impressionist": 0.65,
                "contemporary": 0.5}.get(self.style.era, 0.5)
        if sec.bars >= 12:
            base += 0.12
        if sec.role in ("development", "transition"):
            base += 0.1
        return max(0.05, min(0.95, base))

    def _right_hand(self, sec: SectionPlan, key: Key, timeline: HarmonyTimeline,
                    melody: list[Note], bar_ticks: int, beat_ticks: int) -> list[Note]:
        """Realise the right hand in the manner the section calls for."""
        mode = sec.texture_rh or "melody"
        if mode == "chordal":
            return self._chordal_right_hand(melody, key, timeline, sec)
        if mode == "figuration":
            ctx = TextureContext(
                timeline, key, self.rng, bar_ticks=bar_ticks, beat_ticks=beat_ticks,
                low=self.style.rh_range[0] + sec.register * 12,
                high=min(108, self.style.rh_range[1] + sec.register * 12),
                staff=1, voice=1,
                density=min(0.95, self.style.rhythm_density + 0.25 + sec.energy * 0.2),
                style=self.style.name, dynamic=_dyn_level(sec.dynamic),
                hand_span=self.style.hand_span, variety=self._variety(sec))
            name = "scale_run" if sec.role == "cadenza" else "arpeggio"
            figures = render_texture(name, ctx)
            figures = self._crown(figures, melody, bar_ticks, timeline.start)
            # Running passagework is phrased in groups, not left bare; without
            # this a virtuoso etude engraves with no slurs at all.
            self._phrase_figuration(figures, bar_ticks, timeline.start)
            return figures
        if mode == "counterpoint":
            return melody
        return self._doubled(melody, key, timeline, sec)

    def _chordal_right_hand(self, melody: list[Note], key: Key,
                            timeline: HarmonyTimeline, sec: SectionPlan) -> list[Note]:
        """Melody harmonised underneath — the big Rachmaninoff right hand."""
        out: list[Note] = []
        t = timeline.start
        thickness = 2 if sec.energy < 0.7 else 3
        for n in melody:
            if n.grace or not n.pitches:
                out.append(n)
                if not n.grace:
                    t += n.duration
                continue
            top = n.pitches[-1]
            chord = timeline.at(t)
            stack = [top]
            m = top.midi - 1
            floor = max(self.style.rh_range[0], top.midi - self.style.hand_span)
            pcs = set(chord.pcs)
            while len(stack) < thickness + 1 and m >= floor:
                if m % 12 in pcs:
                    stack.append(spell_in_chord(m, chord, key))
                m -= 1
            nn = n.copy()
            nn.pitches = sorted(set(stack), key=lambda p: p.midi)
            if len(nn.pitches) > 2 and n.duration >= HALF:
                nn.arpeggiate = self.rng.random() < 0.2
            out.append(nn)
            t += n.duration
        return out

    def _phrase_figuration(self, notes: list[Note], bar_ticks: int, start: int) -> None:
        """Slur each bar of figuration and accent its first note."""
        t = start
        group_open = False
        for i, n in enumerate(notes):
            at_bar = (t - start) % bar_ticks == 0
            last = i == len(notes) - 1
            if n.pitches and at_bar and not group_open:
                n.slur_start = self._slur_id
                group_open = True
                if self.rng.random() < self.style.articulation_rate:
                    n.articulations = list(set(n.articulations + ["accent"]))
            t += n.duration
            ends = ((t - start) % bar_ticks == 0) or last
            if group_open and ends and n.pitches:
                n.slur_stop = self._slur_id
                self._slur_id = self._slur_id % 6 + 1
                group_open = False

    def _crown(self, figures: list[Note], melody: list[Note], bar_ticks: int,
               start: int) -> list[Note]:
        """Let the melody's structural notes poke through a figuration."""
        peaks: dict[int, Pitch] = {}
        t = start
        for n in melody:
            if not n.grace and n.pitches and t % bar_ticks == 0:
                peaks[t] = n.pitches[-1]
            if not n.grace:
                t += n.duration
        t = start
        out: list[Note] = []
        for n in figures:
            if t in peaks and n.pitches:
                nn = n.copy()
                nn.pitches = [peaks[t]]
                nn.articulations = list(set(nn.articulations + ["accent"]))
                out.append(nn)
            else:
                out.append(n)
            t += n.duration
        return out

    def _doubled(self, melody: list[Note], key: Key, timeline: HarmonyTimeline,
                 sec: SectionPlan) -> list[Note]:
        """Thicken the melody the way the style would."""
        mode = self.style.doubling
        if mode == "none" or sec.energy < 0.55:
            return melody
        out: list[Note] = []
        for n in melody:
            if not n.pitches or n.grace:
                out.append(n)
                continue
            p = n.pitches[0]
            extra: Pitch | None = None
            if mode == "octave" and p.midi - 12 >= self.style.rh_range[0] - 6:
                extra = p.transpose_chromatic(-12).respell(p.alter >= 0)
                extra = key.spell(p.midi - 12)
            elif mode == "thirds":
                extra = p.transpose_diatonic(-2, key)
            elif mode == "sixths":
                extra = p.transpose_diatonic(-5, key)
            elif mode == "chords":
                chord = timeline.at(0)
                extra = spell_in_chord(max(21, p.midi - 5), chord, key)
            if extra is not None and extra.midi < p.midi:
                n = n.copy()
                n.pitches = [extra, p]
            out.append(n)
        return out

    def _write_ensemble(self, score: Score, parts: list[Part], sec: SectionPlan,
                        key: Key, timeline: HarmonyTimeline, melody: list[Note],
                        start_tick: int, bar_ticks: int, beat_ticks: int) -> None:
        from .orchestration import orchestrate
        orchestrate(self, score, parts, sec, key, timeline, melody, start_tick,
                    bar_ticks, beat_ticks)

    # ------------------------------------------------------------------
    def _write_dynamics(self, parts: list[Part], sec: SectionPlan,
                        start_tick: int, bar_ticks: int) -> None:
        main = parts[0]
        base = sec.dynamic or "mf"
        place_direction(main, Direction("dynamics", base, 0, 1, "below",
                                        extra={"dynamics_velocity":
                                               DYN_VELOCITY.get(base, 80)}),
                        start_tick, self.bar_ticks)
        if sec.bars < 4 or self.style.dynamic_volatility < 0.25:
            return
        # One hairpin pair per phrase, so the page shows the same shape the
        # playback does.
        for tick, direction in self.expression.hairpins(
                getattr(self, "_phrases", []), base, staff=1,
                wedge_id_start=self._wedge_id, bar_ticks=bar_ticks):
            place_direction(main, direction, tick, self.bar_ticks)
        self._wedge_id = self._wedge_id % 6 + 1

        # Restate the level once at the section's high point.
        peak_bar = max(1, int(sec.bars * 0.62))
        target = shift_dynamic(base, 1 if sec.energy >= 0.5 else -1)
        place_direction(main, Direction("dynamics", target, 0, 1, "below",
                                        extra={"dynamics_velocity":
                                               DYN_VELOCITY.get(target, 80)}),
                        start_tick + peak_bar * bar_ticks, self.bar_ticks)

    def _write_pedal(self, part: Part, timeline: HarmonyTimeline,
                     start_tick: int, bar_ticks: int) -> None:
        mode = self.style.pedal
        points: list[int] = []
        if mode == "harmonic":
            points = [s.start for s in timeline.spans]
        elif mode == "long":
            t = timeline.start
            while t < timeline.end:
                points.append(t)
                t += bar_ticks
        elif mode == "syncopated":
            points = [s.start + bar_ticks // 4 for s in timeline.spans]
        for i, t in enumerate(points):
            end = points[i + 1] if i + 1 < len(points) else timeline.end
            if end - t < QUARTER:
                continue
            place_direction(part, Direction("pedal", "start", 0, 2, "below"),
                            t, self.bar_ticks)
            place_direction(part, Direction("pedal", "stop", 0, 2, "below"),
                            max(t + QUARTER, end - 1), self.bar_ticks)

    # ------------------------------------------------------------------
    def _finalise(self, score: Score, parts: list[Part], total_bars: int) -> None:
        self._clamp_ranges(parts)
        for part in parts:
            vs = [(1, 1)] if part.staves == 1 else [(1, 1), (5, 2)]
            while len(part.measures) < total_bars:
                part.measure(len(part.measures) + 1)
            fill_empty_measures(part, self.bar_ticks, vs)
            merge_tied_rests(part)
            apply_beams(part, self.time)
            if part.measures:
                part.measures[-1].barline = "light-heavy"
        score.pad_to_equal_length()


    def _clamp_ranges(self, parts: list[Part]) -> None:
        """Last line of defence: no note outside the instrument's real range.

        Octave doubling and register shifts compound, so a nocturne can drift
        into a register no pianist would voice it in; fold such notes back.
        """
        plans = self.plan.instruments or []
        for part, ip in zip(parts, plans):
            lo = max(21, ip.range_low or 21)
            hi = min(108, ip.range_high or 108)
            if lo >= hi:
                continue
            for m in part.measures:
                for notes in m.voices.values():
                    for n in notes:
                        if not n.pitches:
                            continue
                        fixed = []
                        for p in n.pitches:
                            midi = p.midi
                            while midi > hi:
                                midi -= 12
                            while midi < lo:
                                midi += 12
                            fixed.append(p if midi == p.midi else self.key.spell(midi))
                        seen, uniq = set(), []
                        for p in sorted(fixed, key=lambda x: x.midi):
                            if p.midi not in seen:
                                seen.add(p.midi)
                                uniq.append(p)
                        n.pitches = uniq


def _dyn_level(d: str) -> float:
    try:
        return DYN_SCALE.index(d) / (len(DYN_SCALE) - 1)
    except ValueError:
        return 0.5


def compose(plan: CompositionPlan, model=None, progress=None) -> Score:
    return Composer(plan, model, progress).render()
