"""Composing with the trained model as the source of the music itself.

The symbolic engine knows the rules; it does not have taste. A model trained
on real scores has heard how the rules are actually used — which is the part
no amount of rule-writing supplies. So when a checkpoint is present the model
writes the notes, and the engine does what a model is bad at and an engraver
must be right about: keeping every bar full, every chord inside one hand,
every note inside the instrument, and the page properly beamed and marked.

If anything here fails the caller falls back to the symbolic engine, so a
missing, half-trained or mismatched checkpoint can never stop Motif working.
"""
from __future__ import annotations

from ..engrave.beaming import apply_beams
from ..engrave.layout import fill_empty_measures, merge_tied_rests, place_direction
from ..plan import CompositionPlan, InstrumentPlan
from ..score import Direction, Part, Score, bar_duration
from ..theory.pitch import Key
from .expression import DYN_VELOCITY, ExpressionPlanner
from .styles import resolve_style


class NeuralUnavailable(RuntimeError):
    """The model could not produce usable material for this request."""


def compose_neural(plan: CompositionPlan, model, progress=None) -> Score:
    """Write the piece with the model, then make it a real score."""
    style = resolve_style(plan.style)
    key = Key.parse(plan.key)
    time = tuple(plan.time)
    total_bars = max(1, plan.total_bars or sum(s.bars for s in plan.sections) or 16)

    if progress is not None:
        progress("Composing…")
    score = model.generate_long(style=style.name, key=key, time=time,
                                tempo=float(plan.tempo), bars=total_bars,
                                seed=plan.seed or None, progress=progress)
    if not score.parts or score.measure_count < 2:
        raise NeuralUnavailable("the model returned no usable material")

    if progress is not None:
        progress("Voicing and engraving the score…")
    score.title = plan.title
    score.subtitle = plan.subtitle
    score.composer = "Generated by Motif.ai"
    score.key, score.time, score.tempo = key, time, plan.tempo
    score.metadata.update({"prompt": plan.prompt, "style": style.name,
                           "form": plan.form, "seed": plan.seed,
                           "character": plan.character, "ensemble": plan.ensemble,
                           "generator": "neural"})

    instrument = (plan.instruments or [InstrumentPlan()])[0]
    bar_ticks = bar_duration(time)
    for part in score.parts:
        part.name = instrument.name
        part.abbreviation = instrument.abbreviation
        part.midi_program = instrument.midi_program
        _conform_length(part, total_bars, bar_ticks)
        _clamp_to_instrument(part, instrument, key)
        _fit_hands(part, style, key)
        fill_empty_measures(part, bar_ticks, [(1, 1), (5, 2)])
        merge_tied_rests(part)
        apply_beams(part, time)
        if part.measures:
            part.measures[-1].barline = "light-heavy"
            part.measures[-1].key = None
        if part.measures:
            part.measures[0].key = key
            part.measures[0].time = time

    _mark_dynamics(score, plan, style, bar_ticks)
    planner = ExpressionPlanner(_rng(plan), style, float(plan.tempo))
    offsets, running = [], 0
    for sec in plan.sections:
        offsets.append(running)
        running += sec.bars
    if plan.sections:
        score.tempos = planner.tempo_marks(plan.sections, offsets, bar_ticks)
    score.pad_to_equal_length()
    return score


def _rng(plan: CompositionPlan):
    import random
    return random.Random(plan.seed or 0)


def _conform_length(part: Part, total_bars: int, bar_ticks: int) -> None:
    """Exactly the number of bars that were asked for."""
    while len(part.measures) > total_bars:
        part.measures.pop()
    while len(part.measures) < total_bars:
        part.measure(len(part.measures) + 1)
    for i, m in enumerate(part.measures, start=1):
        m.number = i


def _clamp_to_instrument(part: Part, ip: InstrumentPlan, key: Key) -> None:
    lo = max(21, ip.range_low or 21)
    hi = min(108, ip.range_high or 108)
    if lo >= hi:
        return
    for m in part.measures:
        for notes in m.voices.values():
            for n in notes:
                if not n.pitches:
                    continue
                fixed = []
                for p in n.pitches:
                    midi = p.midi
                    while midi > hi:
                        midi -= 12
                    while midi < lo:
                        midi += 12
                    fixed.append(p if midi == p.midi else key.spell(midi))
                seen, uniq = set(), []
                for p in sorted(fixed, key=lambda x: x.midi):
                    if p.midi not in seen:
                        seen.add(p.midi)
                        uniq.append(p)
                n.pitches = uniq


def _fit_hands(part: Part, style, key: Key) -> None:
    from .composer import _fit_to_hand
    reach = max(9, min(14, style.hand_span))
    for m in part.measures:
        for notes in m.voices.values():
            for n in notes:
                if len(n.pitches) > 1:
                    n.pitches = _fit_to_hand(
                        n.pitches, reach, "bottom" if n.staff > 1 else "top")


def _mark_dynamics(score: Score, plan: CompositionPlan, style, bar_ticks: int) -> None:
    """Print a dynamic where each section begins.

    The model gives every note a velocity, which is how it sounds; a reader
    still needs to see the level on the page.
    """
    if not score.parts or not plan.sections:
        return
    main = score.parts[0]
    tick = 0
    for sec in plan.sections:
        mark = sec.dynamic or "mf"
        place_direction(main, Direction("dynamics", mark, 0, 1, "below",
                                        extra={"dynamics_velocity":
                                               DYN_VELOCITY.get(mark, 80)}),
                        tick, bar_ticks)
        tick += sec.bars * bar_ticks
